# Load custom R functions
source("custom_functions/parse_named_args.r")
source("custom_functions/ref_vals_extrapolation.r")
# Read command-line arguments and parse them
args <- commandArgs(trailingOnly = TRUE)
parsed_args <- type.convert.args(args)

# Description of arguments
cat("Usage: Rscript ref_vals_completion.R beta_vals=/full/path/my_beta_vals.rds ref_vals=/full/path/my_ref_vals.rds output_dir=/my/output/dir\n\n")
cat("Arguments:\n\n")
cat("  beta_vals: Provide the full file path to the .rds file containing the beta values.\n\n")
cat("  ref_vals: Provide the full file path to the .rds file containing the reference values generated by the gs_ref_vals.R script.\n\n")
cat("  output_dir: Directory where all outputs will be saved. (default = current working directory)\n\n")

output_dir <- ifelse(!is.null(parsed_args$output_dir), parsed_args$output_dir, getwd())

# Extract the filename from the path
filename <- basename(parsed_args$beta_vals)
parsed_beta_name <- sub("\\.rds$", "", filename)
# Extract the filename from the path
filename <- basename(parsed_args$ref_vals)
parsed_ref_name <- sub("\\.rds$", "", filename)
parsed_ref_name <- sub("^ref_vals_", "", parsed_ref_name)
# Define filename suffix
suffix <- paste0(parsed_beta_name, "_GS_", parsed_ref_name)

# Check if both inputs are BMIQ
beta_has_BMIQ <- grepl("_BMIQ(_|$)", parsed_beta_name)
ref_has_BMIQ  <- grepl("_BMIQ(_|$)", parsed_ref_name)
# Stop if they differ
if (beta_has_BMIQ != ref_has_BMIQ) {
  stop("Inconsistent BMIQ suffix: one of the input files has '_BMIQ' and the other does not.")
}

epiclock_list <- readRDS("scripts/epiclocks/epiclocks_probes_list.rds")
betas <- readRDS(as.character(parsed_args$beta_vals))
ref_vals <- readRDS(as.character(parsed_args$ref_vals))

# Ensure top-level output_dir exists and set working directory
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)
setwd(output_dir)

# Missing probes extrapolation
complete_beta_vals <- ref_vals_extrapolation(beta_vals = betas, 
                                             ref_vals = ref_vals,
                                             epiclocks = epiclock_list, 
                                             suffix = suffix)

# Save each completed matrix as a separate RDS file
saveRDS(complete_beta_vals, file = paste0(suffix, ".rds"))
write.csv(t(complete_beta_vals), paste0(suffix, ".csv"), row.names = TRUE)
cat("Missing probes extrapolation completed successfully!\n")
